### ISSUE TITLE
Py Source

### ISSUE THREAD

**Issue by Adilmar** [abaranovskis-redsamurai/shenzhen#1]
Great job, congratulations could make the font available. And I did not find it in your repository in git.

**Comment by abaranovskis-redsamurai** [comment]
Sorry, could you describe more, what you mean by font ?

**Comment by Adilmar** [comment]
I would like the python code in this tutorial, https://medium.com/oracledevs/text-classification-with-deep-neural-network-in-tensorflow-simple-explanation-be07c6cbe867

I'm studying tensor is your tutorial is helping me a lot I would like to continue.

**Comment by abaranovskis-redsamurai** [comment]
Jupyter notebooks with Python code for this tutorial is here: https://github.com/abaranovskis-redsamurai/shenzhen/tree/master/redsamchatbot

Thanks :)
